# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run . completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run . completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run . completion "fish" >./completions/{{ .ProjectName }}.fish'
changelog:
  disable: true
builds:
  - main: .
    binary: sunbeam
    ldflags:
      - s -w
      - -X github.com/pomdtr/sunbeam/internal/cli.Version={{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  extra_files:
    - glob: internal/schemas/config.schema.json

snapshot:
  version_template: "{{ incpatch .Version }}-next"
brews:
  - name: sunbeam
    homepage: https://sunbeam.pomdtr.me
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "sunbeam"
      bash_completion.install "completions/sunbeam.bash"
      zsh_completion.install "completions/sunbeam.zsh"
      fish_completion.install "completions/sunbeam.fish"

aurs:
  - name: sunbeam-bin
    homepage: https://sunbeam.pomdtr.me
    description: Generate powerful UIs from simple scripts written in any language.
    maintainers:
      - "Achille Lacoin <achille.lacoin@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/sunbeam-bin.git"
    package: |-
      # bin
      install -Dm755 "./sunbeam" "${pkgdir}/usr/bin/sunbeam"
      # license
      install -Dm644 "./LICENSE-MIT" "${pkgdir}/usr/share/licenses/sunbeam/LICENSE"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/sunbeam.bash" "${pkgdir}/usr/share/bash-completion/completions/sunbeam"
      install -Dm644 "./completions/sunbeam.zsh" "${pkgdir}/usr/share/zsh/site-functions/_sunbeam"
      install -Dm644 "./completions/sunbeam.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/sunbeam.fish"
