# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run . completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run . completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run . completion "fish" >./completions/{{ .ProjectName }}.fish'
changelog:
  skip: true
builds:
  - ldflags:
      - -s -w -X github.com/pomdtr/sunbeam/cmd.Version={{.Version}} -X github.com/pomdtr/sunbeam/cmd.Date={{time "2006-01-02"}}
    env:
      - CGO_ENABLED=0
    goos:
      # - windows
      - linux
      - darwin
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
    rlcp: true
nfpms:
  - vendor: pomdtr
    homepage: https://pomdtr.github.io/sunbeam
    maintainer: Achille Lacoin
    description: Generate powerful UIs from simple scripts written in any language.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: ./completions/{{ .ProjectName }}.bash
        dst: /etc/bash_completion.d/{{ .ProjectName }}
      - src: ./completions/{{ .ProjectName }}.fish
        dst: /usr/share/fish/vendor_completions.d/{{ .ProjectName }}.fish
      - src: ./completions/{{ .ProjectName }}.zsh
        dst: /usr/share/zsh/site-functions/_{{ .ProjectName }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: sunbeam
    homepage: https://pomdtr.github.io/sunbeam
    tap:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "sunbeam"
      bash_completion.install "completions/sunbeam.bash"
      zsh_completion.install "completions/sunbeam.zsh"
      fish_completion.install "completions/sunbeam.fish"
scoop:
  bucket:
    owner: pomdtr
    name: scoop-bucket
  folder: bucket
  homepage: https://pomdtr.github.io/sunbeam
  description: Generate powerful UIs from simple scripts written in any language.
  license: MIT
