rootItems:
  - title: Browse Developer Directory
    command: browse-files
    extension: file-browser
    with:
      root: ~/Developer
  - title: List my Repositories
    command: list-repos
    extension: github
    with:
      owner: pomdtr
