name: Web

on:
  push:
    branches:
      - main

jobs:
  web:
    name: Build and deploy site and docs
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
        working-directory: www
      - run: npm run build
        working-directory: www
      - uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -rv --delete
          path: www/.vitepress/dist/
          remote_path: /home/pomdtr.me/smallweb/sunbeam
          remote_host: ssh.pomdtr.me
          remote_user: pomdtr.me
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
